// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuIZP5VUplmHw4wWdHo8t2Rk__ajeIEfQ',
    appId: '1:95080981655:web:1e06df68e942dae78335d2',
    messagingSenderId: '95080981655',
    projectId: 'examen-4-8ff96',
    authDomain: 'examen-4-8ff96.firebaseapp.com',
    storageBucket: 'examen-4-8ff96.appspot.com',
    measurementId: 'G-LYEXPWQQSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3c2fFvGSGvFc05it06zDhms5sU-wbhIo',
    appId: '1:95080981655:android:ee9f7cc3582e52b38335d2',
    messagingSenderId: '95080981655',
    projectId: 'examen-4-8ff96',
    storageBucket: 'examen-4-8ff96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZyxu6FmB_7RnYdHFvOBjtenCQYkVIjZo',
    appId: '1:95080981655:ios:ca24f2055fa170bd8335d2',
    messagingSenderId: '95080981655',
    projectId: 'examen-4-8ff96',
    storageBucket: 'examen-4-8ff96.appspot.com',
    iosBundleId: 'com.example.examen4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZyxu6FmB_7RnYdHFvOBjtenCQYkVIjZo',
    appId: '1:95080981655:ios:ca24f2055fa170bd8335d2',
    messagingSenderId: '95080981655',
    projectId: 'examen-4-8ff96',
    storageBucket: 'examen-4-8ff96.appspot.com',
    iosBundleId: 'com.example.examen4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuIZP5VUplmHw4wWdHo8t2Rk__ajeIEfQ',
    appId: '1:95080981655:web:5c9741c6587269818335d2',
    messagingSenderId: '95080981655',
    projectId: 'examen-4-8ff96',
    authDomain: 'examen-4-8ff96.firebaseapp.com',
    storageBucket: 'examen-4-8ff96.appspot.com',
    measurementId: 'G-1HJBHHWMYW',
  );
}
